### ISSUE TITLE
Old version of WeGlide frontend delivered

### ISSUE THREAD

**Issue by p-bartczak** [weglide/bugtracker#154] opened 2022-01-06 12:06 UTC
**Describe the bug**
There is no tab National in the PC version when you start to use WeGlide.org. After clicking Ranks icon appears https://weglide.org/ranking/free?season=2022&category=pilot&user=ALL&sc_class=ALL page. See https://www.screenpresso.com/=Wnl5f
You need to refresh page to see National. Appears https://www.weglide.org/ranking/free?season=2022&category=pilot
It isn't a question of cache. I cleaned the cache. **It is very confusing**. 

MS Edge is OK. Chrome had this problem.

**Device (please complete the following information):**
 - Device: Lenovo notebook
 - OS: Windows 10, Windows 11
 - Browser : Chrome

**Comment by flyingjoe** [comment] 2022-01-06 12:58
Thanks for reporting @p-bartczak, we are aware of this issue. This bug was caused by moving weglide.org to www.weglide.org. We have identified  a possible fix but it will take some more time to be implemented.

A temporary workaround is to deregister WeGlides' service worker:
Press F12 -> Switch to tab "Application" -> "Service Workers"  -> "Unregister"

**Comment by p-bartczak** [comment] 2022-01-08 19:42
Please, let me know when it's fixed. As I mentioned it's confusing. Older pilots who aren't familiar with computers can have problem with it.

**Comment by samuel-git** [comment] 2022-01-28 14:50
Only affects users who visited weglide before august 2021 on the same device.
Everyone who joined afterwards is fine.
Also visiting www.weglide.org directly should fix the issue as well.

**Comment by p-bartczak** [comment] 2022-01-31 06:57
"Only affects users who visited weglide before august 2021 on the same device" - so it affects most of users. I think more than 90%. It's worth to resolve it.
IMHO most of people drop www using web address. It's good practice according Google e.g.

**Comment by samuel-git** [comment] 2022-01-31 09:35
Definitely worth resolving. But will take some more time.
Currently less than 2% of our users is affected by this caching issue.

**Comment by p-bartczak** [comment] 2022-02-09 09:43
So when it will be resolved? I can't understand why it's a problem. Redirect or something else - I think there is some simple solutions. I'm former IT specialist - I did what you suggested e.g. ("Press F12 -> Switch to tab "Application" -> "Service Workers" -> "Unregister") and I have still the problem present.  So when? Are you able to declare any date?

**Comment by samuel-git** [comment] 2022-02-09 17:04
No timeline yet.
It should definitely be resolved after unregistering the service worker. Might need a reload/browser restart after that.
MS Edge is based on Chrome so there should not be a difference.
Very hard for us to debug as we do not have browsers stuck on old versions to reproduce.

**Comment by samuel-git** [comment] 2022-05-10 21:22
Closing because less than 0.1% of users affected now according to our statistics.

**Closed by samuel-git** 2022-05-10 21:22 UTC
Labels: bug

**Comment by samuel-git** [comment] 2022-07-22 13:29
Automatic redirect which kills old service workers is installed since one week. Should not be possible to get an old version anymore. Please report if this somehow happens again. 👍
