### ISSUE TITLE
Altitude wrong (offset) in Weglide compared to SeeYou

### ISSUE THREAD

**Issue by UliBrunet** [weglide/bugtracker#227] opened 2023-05-10 16:42 UTC
**Describe the bug**
In flight https://www.weglide.org/flight/240697 there seems to be an offset of about minus 200m of the Altitude shown. If the Logfile is opened in SeeYou, the correct altitude is shown.

**To Reproduce**
1. Go to https://www.weglide.org/flight/240697
2. Download the ICG file
3. Openit in SeeYou

**Expected behavior**
correct display in WeGlide

**Screenshots**
n/a

**Device (please complete the following information):**
 - Device: LX8040
 - OS: LX
 - Browser Firefox

**Comment by k-grosser** [comment] 2023-05-20 07:29
I encountered a similar issue:

**Describe the bug**
I uploaded some old flights from OLC, several of them have a large altitute offset from around +850m and are thus shown as invalid with a QNH out of range, although the flights were originally valid with correct altitude in OLC and at the time SeeYou.

**To Reproduce**
 See, e.g.,
[https://www.weglide.org/flight/262084](https://www.weglide.org/flight/262084) on we glide
and its counterpart on OLC
[https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=1416966#map=](https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=1416966#map=)

**Expected behavior**
correct display in WeGlide

**Screenshots**
Altitude weglide
![Screenshot 2023-05-20 at 09-27-58 349 km · Katharina Großer · Koblenz-Winningen 18 07 2010](https://github.com/weglide/bugtracker/assets/43414739/2224c2b9-09c4-4259-83b4-9e43e389ffa4)

Altitude OLC
![Screenshot 2023-05-20 at 09-28-07 OLC Fluginformation - Katharina Großer (DE) - 18 07 2010](https://github.com/weglide/bugtracker/assets/43414739/b7461146-27f1-4198-84c7-344ce1ac2f64)

**Device (please complete the following information):**

- Device: LX5000IGC
- OS: LX
- Browser Firefox

**Comment by moldhouse** [comment] 2023-05-20 10:43
These are, in fact, two separate issues. The first one was an incorrect altitude when the recording started in the air, which is now fixed. Thanks for making us aware @UliBrunet.

The second one concerns a wrong pressure altitude in the file. @k-grosser, your pressure altitude at the start is written as 1200m, so there seems to be a problem with the logger. It is right to display the error message, but we should still correct the altitude with ground level and GPS altitude, which is also now fixed.

**Closed by moldhouse** 2023-05-20 10:43 UTC
Labels: bug
