### ISSUE TITLE
Ctrl-LMB or Shift-LMB opens flight also in current tab

### ISSUE THREAD

**Issue by obetz** [weglide/bugtracker#168] opened 2022-04-24 19:51 UTC
**Describe the bug**
Ctrl - left mouse click on a "Zeigen" link in a flight list does not only open the flight details in a new browser tab but also in the current tab.

**To Reproduce**
1. Display a flight list with Firefox
2. Ctrl-Click on a flight's 'zeigen' link
3. The flight details are shown in a new tab (as intended) _and also in the current tab_.

The same applies to Shift-Left click (opens details in a new window _and_ in current tab)

**Expected behavior**
The flight details are shown in a new tab, while the current tab remains unchanged

BTW: Right click -> "Open link in new tab" works correctly. Do you fiddle with my keystrokes?

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser Firefox

**Comment by samuel-git** [comment] 2022-04-27 22:56
Should be fixed now. Please re-open when you encounter this again (could not reproduce properly on Mac).

**Closed by samuel-git** 2022-04-27 22:56 UTC
Labels: bug
