### ISSUE TITLE
Overlapping issue when resizing the window

### ISSUE THREAD

**Issue by dibstan** [weglide/bugtracker#25] opened 2020-12-27 17:06 UTC
**Describe the bug**
Refitting all objects to a different window size doesn't work on the left side of the screen.

**To Reproduce**
1. Go to the main page in full screen or on right-half screen.
2. Pull the window to the left side of the screen to resize it to the right half of the screen.
3. See that some objects are overlapping.

**Expected behavior**
Nothing is overlapping.

**Screenshots**

![Weglide-Sizingbug](https://user-images.githubusercontent.com/61154471/103175915-12909600-486e-11eb-98cb-c6df50aee740.JPG)

**Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Browser: Chrome

**Comment by samuel-git** [comment] 2020-12-27 22:00
@dibstan thanks for reporting.

The issue is due to windows and chrome not interacting properly on window halving.
Definitely out of our control, sadly. Maybe we can find a workaround.

Slowly resizing the window should work and confirm that the stylesheets are working correctly.

**Comment by samuel-git** [comment] 2020-12-29 19:49
I am closing this for now, will re-open if I have a workaround.

**Closed by samuel-git** 2020-12-29 19:49 UTC
Labels: UX
