### ISSUE TITLE
Aircraft selection is unintuitive

### ISSUE THREAD

**Issue by niggli** [weglide/bugtracker#8] opened 2020-12-24 21:05 UTC
**Describe the bug**
I noticed that in my flight (https://beta.weglide.org/flights/1960) the ENL was not interpreted which lead to a too high score. The problem was that the type of plane is "Ventus 2" and cannot be changed to "Ventus 2cxT 18m". The "x" is probably not very important, but there should be an 18m "T" variant.

**Comment by CarstenSon** [comment] 2020-12-24 21:16
Hi niggli,
if I try to change the type of glider theres is the "Ventus 2cT 18m" option, so I'm not quite sure if that plane is actually missing.
![grafik](https://user-images.githubusercontent.com/21118388/103106389-6cf2e200-4635-11eb-90a3-063e5490e568.png)

The gliderlist that WeGlide is based on is a github repository as well:
https://github.com/weglide/GliderList/

**Comment by niggli** [comment] 2020-12-24 21:27
OK, now since I changed it to "Ventus 2cM 18m", a lot of additional types have appeared, which means the problem is not that the type doesn't exist at all. But now I can't change back to a pure glider (maybe that's wanted behaviour)

For testing I uploaded another flight I made with the same glider, and selected "Ventus 2" when saving it. Link: https://beta.weglide.org/flights/2561

For this flights I can only select the following types when changing it:

<img width="530" alt="Bildschirmfoto 2020-12-24 um 22 24 18" src="https://user-images.githubusercontent.com/529670/103106563-e0e1ba00-4636-11eb-9307-46bd5a92e2f3.png">
<img width="538" alt="Bildschirmfoto 2020-12-24 um 22 24 13" src="https://user-images.githubusercontent.com/529670/103106564-e212e700-4636-11eb-896a-3d1fc6a8b76e.png">
<img width="537" alt="Bildschirmfoto 2020-12-24 um 22 24 06" src="https://user-images.githubusercontent.com/529670/103106565-e212e700-4636-11eb-8964-f31a4f6cd02e.png">
<img width="541" alt="Bildschirmfoto 2020-12-24 um 22 24 01" src="https://user-images.githubusercontent.com/529670/103106566-e2ab7d80-4636-11eb-9418-cc75141062f4.png">

So the issue is: I cannot change the type of glider from "Ventus 2" to "Ventus 2cxT 18m".

**Comment by flyingjoe** [comment] 2020-12-24 21:38
Hi Niggli, 
Thanks for opening an issue! I can't reproduce the issue you are having. I'm assuming you're using Safari in Catalina? You should be able to just type in an additional "ct" and your Ventus should show up.

**Comment by CarstenSon** [comment] 2020-12-24 21:39
@flyingjoe : If you want the 2cx models included, i've opened a pull request on the GliderList repository - if not thats fine for me as well 👍

**Comment by flyingjoe** [comment] 2020-12-24 21:41
@CarstenSon Thanks!

**Comment by niggli** [comment] 2020-12-24 21:50
Yes, safari in Catalina. Sorry I didn't add that at first, because I thought it's just a matter of the list. However I can also reproduce in Edge in Win10, by just clicking on the plane type in the editing window without adding text, which I intuitively did.   If the text in the field is "Ventus 2", then the "Ventus 2cT 18m" doesn't show up. If the text is "Ventus 2c", it shows up.

So probably this issue is only a very very minor usability thing which will probably occur to nobody except me :)

**Comment by samuel-git** [comment] 2020-12-24 21:55
@niggli a user interface you have to explain, is not a good one (or similar). This is partly an issue with our backend search engine an how it treats recommendations as well as a better indication to keep typing in the frontend. Will improve in the coming weeks. Thanks!

**Comment by CarstenSon** [comment] 2020-12-24 22:02
@samuel-git Have you guys considered a user-specific or registration-driven cache for the suggestions? Something similar to a "most recently used" display.

**Comment by flyingjoe** [comment] 2020-12-25 11:54
@CarstenSon Yes, we considered this already and it would be a great improvement for the quality of our search results. Since this is rather a "nice to have" we pushed it back a little and will revisit it once we are done with the more urgent topics :)

**Comment by samuel-git** [comment] 2020-12-29 19:47
This should be fixed with next release.

**Closed by samuel-git** 2020-12-29 19:47 UTC
Labels: UX, backend
